language: r
sudo: required
cache: packages
warnings_are_errors: true

r:
  - release

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

r_packages:
  - devtools
  - sessioninfo
  - data.table

r_github_packages:
  - rstudio/bookdown
  - r-lib/sessioninfo
  - osofr/simcausal
  - osofr/condensier
  - tpospisi/RFCDE/r
  - tlverse/hal9001@master
  - tlverse/delayed@master
  - tlverse/origami@master
  - tlverse/sl3@master
  - tlverse/tmle3@master
  - tlverse/tmle3mopttx@5ba5f65
  - tlverse/tmle3shift@master
  - nhejazi/haldensify@master

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - test $TRAVIS_BRANCH = "master" && ./_deploy.sh
